# Generated by Django 4.1.2 on 2023-09-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('News', '0001_initial'),
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_content',
            name='dekan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.dekan'),
        ),
        migrations.AddField(
            model_name='news_content',
            name='yangiliklar',
            field=models.ManyToManyField(to='News.newscategory'),
        ),
    ]
