# Generated by Django 4.1.2 on 2023-10-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_content',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_content',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
