# Generated by Django 4.1.2 on 2023-10-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
        ('News', '0003_news_content_img_alter_news_content_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_content',
            name='Leadership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.leadership'),
        ),
        migrations.AddField(
            model_name='news_content',
            name='kafedramanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.kafedramanager'),
        ),
    ]
