# Generated by Django 4.1.2 on 2023-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_popularstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularstudents',
            name='img',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
