# Generated by Django 4.1.2 on 2023-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_popularstudents_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_content',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
