# Generated by Django 4.1.2 on 2023-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_vedio_new_title_en_vedio_new_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='new_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='new_category_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='new_category_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='new_category_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
