# Generated by Django 4.1.2 on 2023-09-20 09:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('title_en', ckeditor.fields.RichTextField(null=True)),
                ('title_uz', ckeditor.fields.RichTextField(null=True)),
                ('title_ru', ckeditor.fields.RichTextField(null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Councils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('title_en', ckeditor.fields.RichTextField(null=True)),
                ('title_uz', ckeditor.fields.RichTextField(null=True)),
                ('title_ru', ckeditor.fields.RichTextField(null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_type_en', models.CharField(max_length=100, null=True)),
                ('document_type_uz', models.CharField(max_length=100, null=True)),
                ('document_type_ru', models.CharField(max_length=100, null=True)),
                ('document_name', models.CharField(max_length=500)),
                ('document_name_en', models.CharField(max_length=500, null=True)),
                ('document_name_uz', models.CharField(max_length=500, null=True)),
                ('document_name_ru', models.CharField(max_length=500, null=True)),
                ('document', models.FileField(upload_to='pdf/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('report_type_en', models.CharField(max_length=100, null=True)),
                ('report_type_uz', models.CharField(max_length=100, null=True)),
                ('report_type_ru', models.CharField(max_length=100, null=True)),
                ('quarter', models.CharField(max_length=100)),
                ('quarter_en', models.CharField(max_length=100, null=True)),
                ('quarter_uz', models.CharField(max_length=100, null=True)),
                ('quarter_ru', models.CharField(max_length=100, null=True)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UZFI.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_en', ckeditor.fields.RichTextField(null=True)),
                ('name_uz', ckeditor.fields.RichTextField(null=True)),
                ('name_ru', ckeditor.fields.RichTextField(null=True)),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unversit_name', models.CharField(max_length=100)),
                ('unversit_name_en', models.CharField(max_length=100, null=True)),
                ('unversit_name_uz', models.CharField(max_length=100, null=True)),
                ('unversit_name_ru', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('address_en', models.CharField(max_length=100, null=True)),
                ('address_uz', models.CharField(max_length=100, null=True)),
                ('address_ru', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('mfo', models.CharField(max_length=100)),
                ('INN', models.CharField(max_length=100)),
                ('OKONX', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_en', ckeditor.fields.RichTextField(null=True)),
                ('name_uz', ckeditor.fields.RichTextField(null=True)),
                ('name_ru', ckeditor.fields.RichTextField(null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('views', models.IntegerField(default=0)),
                ('salary', models.CharField(max_length=100)),
                ('department', ckeditor.fields.RichTextField()),
                ('department_en', ckeditor.fields.RichTextField(null=True)),
                ('department_uz', ckeditor.fields.RichTextField(null=True)),
                ('department_ru', ckeditor.fields.RichTextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KafedraTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/')),
                ('biography', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UZFI.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='KafedraManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('acceptance', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/')),
                ('duties', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UZFI.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Dekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('acceptance', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/')),
                ('duties', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UZFI.faculty')),
            ],
        ),
    ]
