# Generated by Django 4.1.2 on 2023-10-12 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedramanager',
            name='scientific_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.scientificwork'),
        ),
        migrations.AlterField(
            model_name='kafedramanager',
            name='kafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kafedra', to='UZFI.kafedra'),
        ),
        migrations.AlterField(
            model_name='kafedramanager',
            name='kafedramanager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kafedramanager', to=settings.AUTH_USER_MODEL),
        ),
    ]
