# Generated by Django 4.1.2 on 2023-10-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centersdepartmentsmanager',
            name='centers_departments',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UZFI.centersdepartments'),
        ),
    ]
