# Generated by Django 4.1.2 on 2023-09-20 10:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekan',
            name='acceptance_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='acceptance_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='acceptance_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='address_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='duties_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='duties_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='duties_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='faculty_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.faculty'),
        ),
        migrations.AddField(
            model_name='dekan',
            name='faculty_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.faculty'),
        ),
        migrations.AddField(
            model_name='dekan',
            name='faculty_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.faculty'),
        ),
        migrations.AddField(
            model_name='dekan',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='body_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='about_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='about_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='about_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
