# Generated by Django 4.1.2 on 2023-10-06 11:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(blank=True, max_length=100, null=True)),
                ('article_level', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='dekan',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dekan',
            name='scientific_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UZFI.scientificwork'),
        ),
    ]
