# Generated by Django 4.1.2 on 2023-10-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific', to=settings.AUTH_USER_MODEL),
        ),
    ]
