# Generated by Django 4.1.2 on 2023-09-19 09:59

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialstatements',
            old_name='chorak',
            new_name='quarter',
        ),
        migrations.AddField(
            model_name='charter',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='charter',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='charter',
            name='title_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='charter',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='councils',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='councils',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='councils',
            name='title_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='councils',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialstatements',
            name='quarter_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialstatements',
            name='quarter_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialstatements',
            name='report_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialstatements',
            name='report_type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='name_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='name_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='requisites',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisites',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisites',
            name='unversit_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisites',
            name='unversit_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='department_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='department_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='name_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='name_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
