# Generated by Django 4.1.2 on 2023-09-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_alter_dekan_dekan_alter_user_role_managerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekan',
            name='dekan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UZFI.dekanprofile'),
        ),
    ]
