# Generated by Django 4.1.2 on 2023-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_scientificwork_dekan_biography_dekan_scientific_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificwork',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
