# Generated by Django 4.1.2 on 2023-09-21 11:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_dekan_acceptance_en_dekan_acceptance_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedramanager',
            name='acceptance_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='acceptance_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='acceptance_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='address_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='duties_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='duties_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='duties_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedramanager',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
