# Generated by Django 4.1.2 on 2023-10-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_alter_centersdepartmentsmanager_centers_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekan',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='UZFI.faculty'),
        ),
        migrations.AlterField(
            model_name='kafedramanager',
            name='kafedra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kafedra', to='UZFI.kafedra'),
        ),
    ]
