# Generated by Django 4.1.2 on 2023-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_alter_scientificwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councils',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
