# Generated by Django 4.1.2 on 2023-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0002_alter_dekan_acceptance_alter_dekan_acceptance_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
