# Generated by Django 4.1.2 on 2023-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0003_alter_councils_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councils',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
