# Generated by Django 4.1.2 on 2023-09-21 12:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0003_kafedramanager_acceptance_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedrateacher',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='address_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='biography_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='biography_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='biography_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kafedrateacher',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
