# Generated by Django 4.1.2 on 2023-09-23 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0003_alter_dekan_dekan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekan',
            name='dekan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
