# Generated by Django 4.1.2 on 2023-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0004_alter_dekan_dekan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dekan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
