# Generated by Django 4.1.2 on 2023-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0004_alter_kafedramanager_acceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('DEKAN', 'DEKAN'), ('KAFEDRAMANAGER', 'KAFEDRAMANAGER'), ('TEACHER', 'TEACHER')], default='TEACHER', max_length=50),
        ),
    ]
