# Generated by Django 4.1.2 on 2023-09-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UZFI', '0005_user_is_dekan_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DekanProfile',
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
    ]
